### PR TITLE
App drawer, fab buttons, search function

### PR DESCRIPTION
**Pull request by ghost**
Hi,

I'm relatively new here and not a real developer. I even don't know really how "pull requests work". I forked your app and added navigation drawer, fab buttons and a search feature. I also changed same minor things. (Nearly) All changes are "tagged" with "// BY ME" in the code. Hope you can do something with my changes. I hope this is the right way.

Regards
scoute-dich

### CODE REVIEW

**Comment by mdev88** [comment]
Hey, I really apreciate your work! I will definetily take a look at what you've done in the next few days and post an update including them.

Thank you!

**Comment by mdev88** [comment]
I'm also new to this pull request thingy...

I tried to pull your changes from here but due to some conflicts I had to do it via the command line, and I don't know if this is normal or I made a mistake, but I am missing some files that you created in your project:

/Archivos/Trabajo/Android Studio Workspace/DiasporaNativeWebApp/app/src/main/res/layout/activity_main.xml
Error:(18, 21) No resource found that matches the given name (at 'layout' with value '@layout/tool_bar').
Error:(40, 47) No resource found that matches the given name (at 'fab_addButtonColorNormal' with value '@color/fab_big').
Error:(41, 48) No resource found that matches the given name (at 'fab_addButtonColorPressed' with value '@color/fab_big_pressed').
Error:(42, 49) No resource found that matches the given name (at 'fab_addButtonPlusIconColor' with value '@color/white').
Error:(53, 42) No resource found that matches the given name (at 'fab_colorNormal' with value '@color/fab_small').
Error:(54, 35) No resource found that matches the given name (at 'fab_icon' with value '@drawable/fab_exit').
Error:(56, 43) No resource found that matches the given name (at 'fab_colorPressed' with value '@color/fab_small_pressed').
Error:(65, 42) No resource found that matches the given name (at 'fab_colorNormal' with value '@color/fab_small').
Error:(66, 35) No resource found that matches the given name (at 'fab_icon' with value '@drawable/fab_edit').
Error:(68, 43) No resource found that matches the given name (at 'fab_colorPressed' with value '@color/fab_small_pressed').
Error:(77, 42) No resource found that matches the given name (at 'fab_colorNormal' with value '@color/fab_small').
Error:(78, 35) No resource found that matches the given name (at 'fab_icon' with value '@drawable/fab_top').
Error:(80, 43) No resource found that matches the given name (at 'fab_colorPressed' with value '@color/fab_small_pressed').
Error:(88, 42) No resource found that matches the given name (at 'fab_colorNormal' with value '@color/fab_small').
Error:(89, 35) No resource found that matches the given name (at 'fab_icon' with value '@drawable/fab_search').
Error:(91, 43) No resource found that matches the given name (at 'fab_colorPressed' with value '@color/fab_small_pressed').
Error:(106, 27) No resource found that matches the given name (at 'headerLayout' with value '@layout/header').
Error:(107, 19) No resource found that matches the given name (at 'menu' with value '@menu/drawer').
/Archivos/Trabajo/Android Studio Workspace/DiasporaNativeWebApp/app/src/main/res/layout/activity_splash.xml
Error:(10, 22) No resource found that matches the given name (at 'src' with value '@drawable/splash_by_me').

It looks that I am missing some XML files.

I will try to grab them from your repository or something and put them in place.

**Comment by mdev88** [comment]
Weird... I have cloned your project and still can't find the missing resources. Maybe you didn't upload all the changes to github or they got caught in the .gitignore or something...?

**Comment by ghost** [comment]
Hi,

sorry for the issues. It is my mistake. I added now the whole project folder to git. I think now all resources are uploaded. I'm new in android development and github. So if there are problems be patient with me and tell me. I want to learn and hope I could help a little bit.

**Comment by mdev88** [comment]
That's cool man, I'm also pretty new to both git and Android dev. 

I will try again later today and if there's any other issues I will let you know.

Thanks!

**Comment by ghost** [comment]
;-)

**Comment by mdev88** [comment]
Done! Great work man!

I have found a couple of details I will change when I have the time. And by the way, I can't find the "Search" option anywhere...

**Comment by mdev88** [comment]
I found it! :D

**Pull request closed without merging**
